print ("Nama : Jourdy Lukiano Matthew Sirait")
print ("NIM  : I0322060")
print ("Asal : Jakarta")
print ("===============================================")
print ("Jakarta merupakan kota dengan penduduk terbesar di indonesia")
print ("Jakarta juga merupakan kota yang terkenal sebagai pusat perekonomian,keuangan,politik dan budaya di Indonesia")
print ("Jakarta memiliki banyak tempat belanja modern seperti mal dan juga berbagai acara budaya seperti konser musik,festival dan acara olahraga") 
print ("Jakarta juga memiliki banyak tempat menarik seperti Monas,Istana Merdeka,Istana Negara dan Taman Mini Indonesia Indah")
print ("Selain itu Jakarta juga memiliki beberapa tantangan,termasuk masalah kemacetan lalu lintas")
print ("=================================================================================================")
print ("Harapan saya menjadi lulusan Teknik Industri adalah saya mampu berkompetensi dengan saingan saya di dunia kerja nanti")
print ("__________________________________________________________________________________________________________________________")